import './globals.css'
import { Roboto } from 'next/font/google'

const fontRoboto = Roboto({ weight: ['700', '400'], style: ["normal"], subsets: ["cyrillic"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fontRoboto.className}>{children}</body>
    </html>
  )
}
